name: mental_health_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies (Updated versions)
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  fl_chart: ^0.63.0
  percent_indicator: ^4.2.4
  url_launcher: ^6.3.1

  # State Management
  riverpod: ^2.6.1

  # UI Enhancements
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0

  # Dependency for AI-related processing (Optional for now)
  http: ^1.3.0

  # Image Picker (For profile pictures if needed)
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/analytics.jpeg
    - assets/ai_bot.jpeg
    - assets/mood.jpg
    - assets/peace.jpg
    - assets/x.jpeg
    - assets/gmail.png
    - assets/fb.jpeg
    - assets/ocd_chart.png
    - assets/ai_interact.jpeg
    - assets/ocd_book.png
    - assets/ocd_video.jpeg
    - assets/therapy.jpeg
    - assets/stress_book.jpeg
    - assets/stress_meter.jpg
    - assets/stress_video.jpeg
    
