// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1UxYDwCyRQpn70oaE4xIPaNPi092fraE',
    appId: '1:802612802196:web:6947cc3ebc03dda0befa81',
    messagingSenderId: '802612802196',
    projectId: 'mentalhealthapp-76ea2',
    authDomain: 'mentalhealthapp-76ea2.firebaseapp.com',
    storageBucket: 'mentalhealthapp-76ea2.firebasestorage.app',
    measurementId: 'G-YTNJ3B0FVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD07CGqXBZpGTum42Ble-yqWVhsi0mBcmM',
    appId: '1:802612802196:android:ccaa30741f273825befa81',
    messagingSenderId: '802612802196',
    projectId: 'mentalhealthapp-76ea2',
    storageBucket: 'mentalhealthapp-76ea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc5NzB_C5jivBUUuzhaLu_SDkWWDjrodc',
    appId: '1:802612802196:ios:b5b50fed26693fe2befa81',
    messagingSenderId: '802612802196',
    projectId: 'mentalhealthapp-76ea2',
    storageBucket: 'mentalhealthapp-76ea2.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
